// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRsMWWj7eU7Iu9ApV9IHLe4GJLFFCrihs',
    appId: '1:192206418049:web:87cb3b41717094164f9d80',
    messagingSenderId: '192206418049',
    projectId: 'gigapp-f7ebc',
    authDomain: 'gigapp-f7ebc.firebaseapp.com',
    storageBucket: 'gigapp-f7ebc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhX55xnBzIHI-jeerphUZOyBASJx1tb24',
    appId: '1:192206418049:android:d8c363a61f13dac24f9d80',
    messagingSenderId: '192206418049',
    projectId: 'gigapp-f7ebc',
    storageBucket: 'gigapp-f7ebc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEoDinbGyt5IyqXAFz-AlUHU9TGPlXL8k',
    appId: '1:192206418049:ios:a72004829301a2e34f9d80',
    messagingSenderId: '192206418049',
    projectId: 'gigapp-f7ebc',
    storageBucket: 'gigapp-f7ebc.firebasestorage.app',
    androidClientId: '192206418049-ektbhkjlpi6v15bodljrlc03da2ge375.apps.googleusercontent.com',
    iosClientId: '192206418049-3jphbal3ua8ha8qbgu2ho34jksvkpmdi.apps.googleusercontent.com',
    iosBundleId: 'com.craftech.gig',
  );
}
